### ISSUE TITLE
Incompatibility with RabbitMQ 2.4.0 ?

### ISSUE THREAD

**Issue by alexgoldstone** [BraveSirRobin/amqphp#1] opened 2011-03-29 13:52 UTC
I am using PHP 5.3.3 and RabbitMQ 2.4.0 and am attempting to run the demo-consumer.php file that is part of the amqphp project. Execution only gets as far as connecting before throwing an error:

<pre>
$conn = new amqp\Connection($config);
$conn->connect();
</pre>

OUTPUT:

<pre>
PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid table key' in /srv/apps/php/lib/amqphp/amqp.wire.php:677
Stack trace:
#0 /srv/apps/php/lib/amqphp/amqp.wire.php(269): amqp_091\wire\Table->offsetSet('?', Object(amqp_091\wire\TableField))
#1 /srv/apps/php/lib/amqphp/amqp.wire.php(250): amqp_091\wire\Reader->readTable()
#2 /srv/apps/php/lib/amqphp/amqp.wire.php(269): amqp_091\wire\Reader->read('F', true)
#3 /srv/apps/php/lib/amqphp/amqp.wire.php(250): amqp_091\wire\Reader->readTable()
#4 /srv/apps/php/lib/amqphp/amqp.wire.php(893): amqp_091\wire\Reader->read('table')
#5 /srv/apps/php/lib/amqphp/amqp.wire.php(823): amqp_091\wire\Method->readMethodContent(Object(amqp_091\wire\Reader), 327)
#6 /srv/apps/php/lib/amqphp/amqp.php(431): amqp_091\wire\Method->readConstruct(Object(amqp_091\wire\Reader))
#7 /srv/apps/php/consumer.php(43): amqp_091\Connection->connect()
#8 {main}
  thrown in /srv/apps/php/lib/amqphp/amqp.wire.php on line 677
</pre>

**Comment by BraveSirRobin** [comment] 2011-03-29 14:46
Hi Alex,

That's very interesting, I must admit I haven't tested Amqphp with the 2.4 Rabbit yet.  I'll run this myself this evening and see if I can sort the issue.

Thanks,
--Robin

**Comment by BraveSirRobin** [comment] 2011-03-29 15:09
Hi Alex,

Looking at this it might be the key you're setting in your Amqp table.  Line 667 in amqp.wire.php fails when the given key item is invalid, it's tests for validity like this:

```
return is_string($k) && $k && (strlen($k) < 129) && preg_match("/[a-zA-Z\$\#][a-zA-Z-_\$\#]*/", $k);
```

Try changing the key value and/or type.

Thanks,
--Robin

**Comment by alexgoldstone** [comment] 2011-03-29 15:37
Hi Robin,

Perhaps I am not doing something I should be but the only keys I am setting are **username**, **userpass** and **vhost** and the error occurs on calling the **connect()** method.

The server itself is listening on the standard port number at localhost.

I have tried your library previously with an earlier version of RabbitMQ and all worked fine so I'm pretty sure I'm not doing anything stupid.

I have reduced my entire test application down to this so you should be able to easily recreate the problem:

<pre>
&lt;?php
use amqp_091 as amqp;
use amqp_091\protocol;
use amqp_091\wire;

require __DIR__ . '/lib/amqphp/amqp.php';

$config = array (
                 'username' => 'guest',
                 'userpass' => 'guest',
                 'vhost' => '/'
                 );

$conn = new amqp\Connection($config);
$conn->connect();
?&gt;
</pre>


On running the above code I get:

<pre>
PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid table key' in /srv/apps/php/lib/amqphp/amqp.wire.php:677
Stack trace:
#0 /srv/apps/php/lib/amqphp/amqp.wire.php(269): amqp_091\wire\Table->offsetSet('?', Object(amqp_091\wire\TableField))
#1 /srv/apps/php/lib/amqphp/amqp.wire.php(250): amqp_091\wire\Reader->readTable()
#2 /srv/apps/php/lib/amqphp/amqp.wire.php(269): amqp_091\wire\Reader->read('F', true)
#3 /srv/apps/php/lib/amqphp/amqp.wire.php(250): amqp_091\wire\Reader->readTable()
#4 /srv/apps/php/lib/amqphp/amqp.wire.php(893): amqp_091\wire\Reader->read('table')
#5 /srv/apps/php/lib/amqphp/amqp.wire.php(823): amqp_091\wire\Method->readMethodContent(Object(amqp_091\wire\Reader), 327)
#6 /srv/apps/php/lib/amqphp/amqp.php(431): amqp_091\wire\Method->readConstruct(Object(amqp_091\wire\Reader))
#7 /srv/apps/php/consumer.php(16): amqp_091\Connection->connect()
#8 {main}
  thrown in /srv/apps/php/lib/amqphp/amqp.wire.php on line 677
</pre>


Thanks,
-- Alex

**Comment by BraveSirRobin** [comment] 2011-03-29 20:51
Hi Alex,

This should be sorted now, there was caused by a bug in Amqphp which I've now fixed, the commit is here:

https://github.com/BraveSirRobin/amqphp/commit/7d2a62f674445eaecaeb23e9cfc6c3d207fa8136

Let me know if you have any further issues with 2.4

Thanks,
--Robin

**Closed as completed** 2011-03-29 20:51 UTC
