### ISSUE TITLE
Incomplete support for 'headers' publish parameter serialization

### ISSUE THREAD

**Issue by lmctv** [BraveSirRobin/amqphp#5] opened 2011-09-12 17:52 UTC
I'm sorry I cannot propose a patch... still, if I try to publish a message with a set of headers as in:

``` php
$p = ...
$publisher = $chan->basic('publish', $p);
$publisher->setContent('text content');
$chan->invoke($publisher);

$p = @array('routing_key' => 'key',
                       'headers' => @array('hdr1' => 'v')
                       ) // v gets published as an integer with value 374

$p = @array(routing_key' => 'key',
                       'headers' => @array('hdr1' => @array( 'hdr2' => 'v'))
                      ) // the inner @array becomes "true" at the broker


$p = @array('routing_key' => 'key',
                       'headers' => @array('hdr1' => 'val1')
                      ) // re-throws an exception, seemingly originated at the broker:

   // Fatal error:  Uncaught exception 'Exception' with message 
   // '[connection.close] reply-code=INTERNAL_ERROR triggered by 
   // (Unknown or unspecified): (reply-code=541) (reply-text=INTERNAL_ERROR)
   // (class-id=0) (method-id=0)  Connection closed OK'

$p = @array('routing_key' => 'key',
                       'headers' => @array('hdr1' => 12)
                      ) // re-throws the very same exception

```

I don't understand where should I look to find the serialization/deserialization code.
If you don't mind pointing me in the right way, and think I can be of any help,  even though 
I'm not a php5 man, I could try and take a stab at the table serialization myself.

Thank you very much, yours
                     l.

**Comment by BraveSirRobin** [comment] 2011-09-12 19:05
Hi,

One thing you posted springs out at me straight away:

```
// Fatal error:  Uncaught exception 'Exception' with message 
// '[connection.close] reply-code=INTERNAL_ERROR triggered by 
// (Unknown or unspecified): (reply-code=541) (reply-text=INTERNAL_ERROR)
// (class-id=0) (method-id=0)  Connection closed OK'
```

The `541` code comes from the RabbitMQ broker, and is defined in the Amqp Spec, here's what it means:

**The server could not complete the method because of an internal error.  The server may require intervention by an operator in order to resume normal operations.**

Check your RabbitMQ server log to see if anything gets output when this error occurs, I suspect there will be, if so post that back here.

I think I know what is causing this error, but I need to see what's in the $p param in the second line of your code snippet: `$publisher = $chan->basic('publish', $p);`   Please could you post back a `var_dump()` of the $p variable just before the call to $chan->basic.

FYI, the Amqp table serialization code is in \amqphp\wire\TableField.php, I suspect the error is caused by the implementation defaulting to an Amqp short string - it seems that the RabbitMQ people tend to use the long string in all cases.

Thanks,
--Robin

**Comment by lmctv** [comment] 2011-09-13 09:39
Robin,
    at first, thank you for such a quick follow-up and the pointer to 
serialization implementation.

I don't think rabbit's logs could be of any help; instead, if you don't 
beat me at it, I'll take a look at the serialization/deserialization 
format.

Have a nice forthweek, yours

```
lorenzo
```

On Mon, 12 Sep 2011, Robin Harvey wrote:

RH> Hi,
RH> 
RH> One thing you posted springs out at me straight away:
RH> 
RH>     // Fatal error:  Uncaught exception 'Exception' with message 
RH>     // '[connection.close] reply-code=INTERNAL_ERROR triggered by 
RH>     // (Unknown or unspecified): (reply-code=541) (reply-text=INTERNAL_ERROR)
RH>     // (class-id=0) (method-id=0)  Connection closed OK'
RH> 
RH> 
RH> The `541` code comes from the RabbitMQ broker, and is defined in the Amqp Spec, here's what it means:
RH> 
RH> **The server could not complete the method because of an internal error.  The server may require intervention by an operator in order to resume normal operations.**
RH> 
RH> Check your RabbitMQ server log to see if anything gets output when this error occurs, I suspect there will be, if so post that back here.
RH> 
RH> 
RH> 
RH> I think I know what is causing this error, but I need to see what's in the $p param in the second line of your code snippet: `$publisher = $chan->basic('publish', $p);`   Please could you post back a `var_dump()` of the $p variable just before the call to $chan->basic.
RH> 
RH> FYI, the Amqp table serialization code is in \amqphp\wire\TableField.php, I suspect the error is caused by the implementation defaulting to an Amqp short string - it seems that the RabbitMQ people tend to use the long string in all cases.
RH> 
RH> 
RH> Thanks,
RH> --Robin
RH> 
RH> -- 
RH> Reply to this email directly or view it on GitHub:
RH> https://github.com/BraveSirRobin/amqphp/issues/5#issuecomment-2074121
RH> 

+-------------------------+----------------------------------------------+
|   Lorenzo M.  Catucci   | Centro di Calcolo e Documentazione           |
| catucci@ccd.uniroma2.it | Università degli Studi di Roma "Tor Vergata" |
|                         | Via O. Raimondo 18 *\* I-00173 ROMA  *\* ITALY |
|  Tel. +39 06 7259 2255  | Fax. +39 06 7259 2125                        |
+-------------------------+----------------------------------------------+

**Comment by lmctv** [comment] 2011-09-13 14:20
A quick follow-up: as you wondered, if I force long encoding for all 
strings, as in the enclosed patch, all goes well.

I'll let you know more as soon as I can.

Yours,

```
lorenzo
```

LMC> RH> 
LMC> RH> I think I know what is causing this error, but I need to see what's in the $p param in the second line of your code snippet: `$publisher = $chan->basic('publish', $p);`   Please could you post back a `var_dump()` of the $p variable just before the call to $chan->basic.
LMC> RH> 
LMC> RH> FYI, the Amqp table serialization code is in \amqphp\wire\TableField.php, I suspect the error is caused by the implementation defaulting to an Amqp short string - it seems that the RabbitMQ people tend to use the long string in all cases.
LMC> RH> 

+-------------------------+----------------------------------------------+
|   Lorenzo M.  Catucci   | Centro di Calcolo e Documentazione           |
| catucci@ccd.uniroma2.it | Università degli Studi di Roma "Tor Vergata" |
|                         | Via O. Raimondo 18 *\* I-00173 ROMA  *\* ITALY |
|  Tel. +39 06 7259 2255  | Fax. +39 06 7259 2125                        |
+-------------------------+----------------------------------------------+

**Comment by BraveSirRobin** [comment] 2011-09-13 18:58
OK, thanks Lorenzo.  I'll close this issue down for now, please re-open it if you need to post that patch or have any other questions.

**Closed as completed by BraveSirRobin** 2011-09-13 18:58 UTC
